;;
;;  cffi-errno  -  Common Lisp wrapper for Unix error codes
;;
;;  Copyright 2017 Thomas de Grivel <thoxdg@gmail.com>
;;
;;  Permission to use, copy, modify, and distribute this software for any
;;  purpose with or without fee is hereby granted, provided that the above
;;  copyright notice and this permission notice appear in all copies.
;;
;;  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
;;  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
;;  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
;;  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
;;  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
;;  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
;;  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
;;

(in-package :cffi-errno)

(include "errno.h")

(cvar ("errno" errno) :int)

(constant (+eperm+ "EPERM"))
(constant (+enoent+ "ENOENT"))
(constant (+esrch+ "ESRCH"))
(constant (+eintr+ "EINTR"))
(constant (+eio+ "EIO"))
(constant (+enxio+ "ENXIO"))
(constant (+e2big+ "E2BIG"))
(constant (+enoexec+ "ENOEXEC"))
(constant (+ebadf+ "EBADF"))
(constant (+echild+ "ECHILD"))
(constant (+eagain+ "EAGAIN"))
(constant (+enomem+ "ENOMEM"))
(constant (+eacces+ "EACCES"))
(constant (+efault+ "EFAULT"))
(constant (+enotblk+ "ENOTBLK"))
(constant (+ebusy+ "EBUSY"))
(constant (+eexist+ "EEXIST"))
(constant (+exdev+ "EXDEV"))
(constant (+enodev+ "ENODEV"))
(constant (+enotdir+ "ENOTDIR"))
(constant (+eisdir+ "EISDIR"))
(constant (+einval+ "EINVAL"))
(constant (+enfile+ "ENFILE"))
(constant (+emfile+ "EMFILE"))
(constant (+enotty+ "ENOTTY"))
(constant (+etxtbsy+ "ETXTBSY"))
(constant (+efbig+ "EFBIG"))
(constant (+enospc+ "ENOSPC"))
(constant (+espipe+ "ESPIPE"))
(constant (+erofs+ "EROFS"))
(constant (+emlink+ "EMLINK"))
(constant (+epipe+ "EPIPE"))
(constant (+edom+ "EDOM"))
(constant (+erange+ "ERANGE"))

(constant (+edeadlk+ "EDEADLK"))
(constant (+enametoolong+ "ENAMETOOLONG"))
(constant (+enolck+ "ENOLCK"))
(constant (+enosys+ "ENOSYS"))
(constant (+enotempty+ "ENOTEMPTY"))
(constant (+eloop+ "ELOOP"))
(constant (+ewouldblock+ "EWOULDBLOCK"))
(constant (+enomsg+ "ENOMSG"))
(constant (+eidrm+ "EIDRM"))
(constant (+echrng+ "ECHRNG"))
(constant (+el2nsync+ "EL2NSYNC"))
(constant (+el3hlt+ "EL3HLT"))
(constant (+el3rst+ "EL3RST"))
(constant (+elnrng+ "ELNRNG"))
(constant (+eunatch+ "EUNATCH"))
(constant (+enocsi+ "ENOCSI"))
(constant (+el2hlt+ "EL2HLT"))
(constant (+ebade+ "EBADE"))
(constant (+ebadr+ "EBADR"))
(constant (+exfull+ "EXFULL"))
(constant (+enoano+ "ENOANO"))
(constant (+ebadrqc+ "EBADRQC"))
(constant (+ebadslt+ "EBADSLT"))
(constant (+edeadlock+ "EDEADLOCK"))
(constant (+ebfont+ "EBFONT"))
(constant (+enostr+ "ENOSTR"))
(constant (+enodata+ "ENODATA"))
(constant (+etime+ "ETIME"))
(constant (+enosr+ "ENOSR"))
(constant (+enonet+ "ENONET"))
(constant (+enopkg+ "ENOPKG"))
(constant (+eremote+ "EREMOTE"))
(constant (+enolink+ "ENOLINK"))
(constant (+eadv+ "EADV"))
(constant (+esrmnt+ "ESRMNT"))
(constant (+ecomm+ "ECOMM"))
(constant (+eproto+ "EPROTO"))
(constant (+emultihop+ "EMULTIHOP"))
(constant (+edotdot+ "EDOTDOT"))
(constant (+ebadmsg+ "EBADMSG"))
(constant (+eoverflow+ "EOVERFLOW"))
(constant (+enotuniq+ "ENOTUNIQ"))
(constant (+ebadfd+ "EBADFD"))
(constant (+eremchg+ "EREMCHG"))
(constant (+elibacc+ "ELIBACC"))
(constant (+elibbad+ "ELIBBAD"))
(constant (+elibscn+ "ELIBSCN"))
(constant (+elibmax+ "ELIBMAX"))
(constant (+elibexec+ "ELIBEXEC"))
(constant (+eilseq+ "EILSEQ"))
(constant (+erestart+ "ERESTART"))
(constant (+estrpipe+ "ESTRPIPE"))
(constant (+eusers+ "EUSERS"))
(constant (+enotsock+ "ENOTSOCK"))
(constant (+edestaddrreq+ "EDESTADDRREQ"))
(constant (+emsgsize+ "EMSGSIZE"))
(constant (+eprototype+ "EPROTOTYPE"))
(constant (+enoprotoopt+ "ENOPROTOOPT"))
(constant (+eprotonosupport+ "EPROTONOSUPPORT"))
(constant (+esocknosupport+ "ESOCKTNOSUPPORT"))
(constant (+eopnotsupp+ "EOPNOTSUPP"))
(constant (+epfnosupport+ "EPFNOSUPPORT"))
(constant (+eafnosupport+ "EAFNOSUPPORT"))
(constant (+eaddrinuse+ "EADDRINUSE"))
(constant (+eaddrnotavail+ "EADDRNOTAVAIL"))
(constant (+enetdown+ "ENETDOWN"))
(constant (+enetunreach+ "ENETUNREACH"))
(constant (+enetreset+ "ENETRESET"))
(constant (+econnaborted+ "ECONNABORTED"))
(constant (+econnreset+ "ECONNRESET"))
(constant (+enobufs+ "ENOBUFS"))
(constant (+eisconn+ "EISCONN"))
(constant (+enotconn+ "ENOTCONN"))
(constant (+eshutdown+ "ESHUTDOWN"))
(constant (+etoomanyrefs+ "ETOOMANYREFS"))
(constant (+etimedout+ "ETIMEDOUT"))
(constant (+econnrefused+ "ECONNREFUSED"))
(constant (+ehostdown+ "EHOSTDOWN"))
(constant (+ehostunreach+ "EHOSTUNREACH"))
(constant (+ealready+ "EALREADY"))
(constant (+einprogress+ "EINPROGRESS"))
(constant (+estale+ "ESTALE"))
(constant (+euclean+ "EUCLEAN"))
(constant (+enotnam+ "ENOTNAM"))
(constant (+enavail+ "ENAVAIL"))
(constant (+eisnam+ "EISNAM"))
(constant (+eremoteio+ "EREMOTEIO"))
(constant (+edquot+ "EDQUOT"))
(constant (+enomedium+ "ENOMEDIUM"))
(constant (+emediumtype+ "EMEDIUMTYPE"))
(constant (+ecanceled+ "ECANCELED"))
(constant (+enokey+ "ENOKEY"))
(constant (+ekeyexpired+ "EKEYEXPIRED"))
(constant (+ekeyrevoked+ "EKEYREVOKED"))
(constant (+ekeyrejected+ "EKEYREJECTED"))
(constant (+eownerdead+ "EOWNERDEAD"))
(constant (+enotrecoverable+ "ENOTRECOVERABLE"))
(constant (+erfkill+ "ERFKILL"))
(constant (+ehwpoison+ "EHWPOISON"))

(constant (+enotsupp+ "ENOTSUPP"))
