
(in-package :common-lisp)

(defpackage :cffi-errno
  (:use :common-lisp :cffi)
  (:export
   #:errno
   #:error-errno
   #:strerror
   #:+perm+
   #:+noent+
   #:+srch+
   #:+intr+
   #:+io+
   #:+nxio+
   #:+2big+
   #:+noexec+
   #:+badf+
   #:+child+
   #:+again+
   #:+nomem+
   #:+acces+
   #:+fault+
   #:+notblk+
   #:+busy+
   #:+exist+
   #:+xdev+
   #:+nodev+
   #:+notdir+
   #:+isdir+
   #:+inval+
   #:+nfile+
   #:+mfile+
   #:+notty+
   #:+txtbsy+
   #:+fbig+
   #:+nospc+
   #:+spipe+
   #:+rofs+
   #:+mlink+
   #:+pipe+
   #:+dom+
   #:+range+
   #:+deadlk+
   #:+nametoolong+
   #:+nolck+
   #:+nosys+
   #:+notempty+
   #:+loop+
   #:+wouldblock+
   #:+nomsg+
   #:+idrm+
   #:+chrng+
   #:+l2nsync+
   #:+l3hlt+
   #:+l3rst+
   #:+lnrng+
   #:+unatch+
   #:+nocsi+
   #:+l2hlt+
   #:+bade+
   #:+badr+
   #:+xfull+
   #:+noano+
   #:+badrqc+
   #:+badslt+
   #:+deadlock+
   #:+bfont+
   #:+nostr+
   #:+nodata+
   #:+time+
   #:+nosr+
   #:+nonet+
   #:+nopkg+
   #:+remote+
   #:+nolink+
   #:+adv+
   #:+srmnt+
   #:+comm+
   #:+proto+
   #:+multihop+
   #:+dotdot+
   #:+badmsg+
   #:+overflow+
   #:+notuniq+
   #:+badfd+
   #:+remchg+
   #:+libacc+
   #:+libbad+
   #:+libscn+
   #:+libmax+
   #:+libexec+
   #:+ilseq+
   #:+restart+
   #:+strpipe+
   #:+users+
   #:+notsock+
   #:+destaddrreq+
   #:+msgsize+
   #:+prototype+
   #:+noprotoopt+
   #:+protonosupport+
   #:+socknosupport+
   #:+opnotsupp+
   #:+pfnosupport+
   #:+afnosupport+
   #:+addrinuse+
   #:+addrnotavail+
   #:+netdown+
   #:+netunreach+
   #:+netreset+
   #:+connaborted+
   #:+connreset+
   #:+nobufs+
   #:+isconn+
   #:+notconn+
   #:+shutdown+
   #:+toomanyrefs+
   #:+timedout+
   #:+connrefused+
   #:+hostdown+
   #:+hostunreach+
   #:+already+
   #:+inprogress+
   #:+stale+
   #:+uclean+
   #:+notnam+
   #:+navail+
   #:+isnam+
   #:+remoteio+
   #:+dquot+
   #:+nomedium+
   #:+mediumtype+
   #:+canceled+
   #:+nokey+
   #:+keyexpired+
   #:+keyrevoked+
   #:+keyrejected+
   #:+ownerdead+
   #:+notrecoverable+
   #:+rfkill+
   #:+hwpoison+
   #:+notsupp+))
